#!/bin/bash

# Compile a tree of files with recipeGrid, preserving the directory structure
# and providing several copies serving differrent numbers of people. (Quick-hack
# script.)

SOURCE="$(readlink -f "$1")"
TARGET="$(readlink -f "$2")"

MIN_SERVINGS=1
MAX_SERVINGS=10

if [ -z "$SOURCE" ] || [ -z "$TARGET" ]; then
	echo "Must supply a source and target directory."
	exit 1
fi

cd "$SOURCE"

# Empty the target directory...
rm -rf "$TARGET"

echo $MAX_SERVINGS

for servings in `seq $MIN_SERVINGS $MAX_SERVINGS`; do
	args="-s $servings"
	subdir="/serves$servings/"
	
	echo $servings
	
	find . -name "*.rec" | while read file; do
		target_file="$TARGET$subdir$file.html"
		mkdir -p "$(dirname "$target_file")"
		recipeGrid "$file" "$target_file" "$args"
	done
done
